version: '3.2'

services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile-web
    networks:
      - my-net
    ports:
      - 9001:80
    volumes:
    - "./www:/usr/share/nginx/html"
  web2:
    build:
      context: .
      dockerfile: Dockerfile-web
    networks:
     - my-net
    ports:
     - 9002:80
    volumes:
      - "./www:/usr/share/nginx/html"
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      - MYSQL_USER=blah
      - MYSQL_PASS=blahblah
    networks:
      - my-net
    ports:
      - 3336:3306
    #volumes:
    #- "./logs_db:/var/log"
  lb:
    build:
      context: .
      dockerfile: Dockerfile-balancer
    networks:
      - my-net
    ports:
      - 9000:80
    #volumes:
    #- "./lb:/var/log/nginx"
networks:
  my-net:
    driver: bridge
