FROM centos:7


MAINTAINER barmaley321 <lkjhlkjh.kjhgjhgkj@yandex.ru>

COPY MariaDB.repo /etc/yum.repos.d/MariaDB.repo

RUN yum -y install mariadb-server mariadb-client

EXPOSE 3306

COPY startup-db.sh /startup.sh

ENTRYPOINT ["/bin/bash","/startup.sh"]

